### PR TITLE
Catch longer JWT segment lengths

### LINKED ISSUE #1207: jwt can not be detected when length doesn't match the regular expression range
**Describe the bug**
json web token cannot be detected successfully If the length of the three parts does not match the range specified in the regular expression.

**To Reproduce**
Given jwt value like this: 
`eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJsb2dnZWQtaW4tdXNlciI6eyJzY29wZWRQZXJtaXNzaW9uIjpbXSwicGVybWlzc2lvbnMiOlsiQS5hZG1pbl9jdXN0b21lcl9kZWxldGUiLCJBLm5vcm1hbF91c2VyX2FwcCIsIkEubm9ybWFsX3VzZXJfY29uZmlndXJhdGlvbiIsIkEubm9ybWFsX3VzZXJfd2VsY29tZV9jb250cm9scyIsIkEubm9ybWFsX3VzZXJfb3JkZXIiLCJBLm5vcm1hbF91c2VyX3NlYXJjaCIsIkEubm9ybWFsX3VzZXJfc2VhcmNoX3BjIiwiQS5ub3JtYWxfdXNlcl9zZWFyY2hfcHJpdmF0ZSIsIkEubm9ybWFsX3VzZXJfcHJpY2luZyIsIkEubm9ybWFsX3VzZXJfcHJpdmF0ZSIsIkEubm9ybWFsX3VzZXJfY29tbWVyY2lhbCIsIkEubm9ybWFsX3VzZXJfcGMiXSwibmFtZSI6WyJUZXN0Il0sIm1haWwiOlsiVGVzdEBleGFtcGxlLmNvbSJdLCJvcmdhbml6YXRpb24iOlsiWC1YeHh4eHguMTIzNCJdLCJsb2NhdGlvbiI6WyIxMjMyMSJdLCJ1bml0IjpbIjEwMyJdLCJjb3VudHJ5IjpbIkNOIl0sInVzZXJUeXBlIjoiZW1wbG95ZWUifSwiaWRlbnRpdHktaWQiOiJNb2NrIn0.EK5TbwsIgde3mT3n7NK2W7TCvpgQQLzshvPPANRQeUmKOv2AWbo_7vNEDTSkwUlaHRN3-dknv8F95p5MsGTzH6Uva8aOPJG6JdBIoYX_ud3aBN-hY1i2Xpf8pqjeINfY3_gDNAB9gdMznEej2uqhPwUXmZtcuWPdUCCeNqPJbRUAJeVXxLr_JtQzO2jmuwNY_YYp7KaEIANZwG1spvLuIGZ0HA03u8ye9c2lfqYcjgfIkjMrwgWPamR7joZOZPdQSO2EHrF7bUWMjRNY-FF5V7tOjEijkknE_nDq5THcEvx1seHYFdFNwy9LSSGGPVmZMKTKQ3UUlZZyBMXcOpOA9w`

I can commit the code successfully and gitleaks cannot detect such leaks.

**Expected behavior**
expect this jwt can be detected and commit should be blocked

**Basic Info (please complete the following information):**
 - OS: MAC OS
 - Gitleaks Version: v8.17.0

**Additional context**

cc @zricethezav

### PR DESCRIPTION
**Pull request by rgmz**
### Description:

This fixes #1207. Ideally, it would be merged after #1215 so the pattern can be made case sensitive.

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by willlindsey05** [comment]
I just encountered a case where the payload length was 756.  Any chance to making the max payload length 1000.

**Comment by rgmz** [comment]
> I just encountered a case where the payload length was 756. Any chance to making the max payload length 1000.

I bumped up the length for each section even further, just to be sure.

@zricethezav any thoughts on this change?

**Comment by rgmz** [comment]
> I bumped up the length for each section even further, just to be sure.

I've since found JWTs that are _even longer_ than 1,000 characters, which is [the highest number of repetitions you can specify](https://github.com/golang/go/blob/4d9ecde/src/regexp/syntax/parse.go#L250). 

In light of this, I've updated this to remove the limit on repetitions. I feel that the pattern is niche enough that this is unlikely to introduce false-positives; I tested this against a large internal GitHub instance and did not get any.

**Comment by zricethezav** [comment]
Thanks for another stellar contribution @rgmz, I'll look into the go-re2 library soon

**Review by Blissful304 — APPROVED** [review]

**Pull request merged**
