### PR TITLE
feat: add new GitLab tokens

### LINKED ISSUE #1401: Add missing GitLab token patterns
Some Gitlab tokens are not detected by Gitleaks (e.g. Deploy token, CI/CD Job token, Feed token, etc.). The complete list of Gitlab token prefixes can be found [here](https://docs.gitlab.com/ee/security/token_overview.html#token-prefixes):

image

cc @zricethezav

### PR DESCRIPTION
**Pull request by bufferoverflow**
Closes #1401

### Description:

Add additional GitLab tokens

### Checklist:

* [x] Does your PR pass tests?
* [x] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by rgmz — COMMENTED** [review]
Looks good. I would add `Entropy: 3` to all, which should filter out any obvious false-positives.

 (I tested these and everything I could find had entropy > 3.)

**Comment by zricethezav** [comment]
@bufferoverflow super! I agree with @rgmz, adding an extra entropy check helps limit the FPs

**Comment by bufferoverflow** [comment]
Thanks for the feedback @rgmz and @zricethezav , I just added `Entropy: 3`  to all the tokens.

**Comment by zricethezav** [comment]
@bufferoverflow my bad on not merging this earlier. Would you mind resolving conflicts? Sorry!

**Comment by zricethezav** [comment]
thank you @bufferoverflow! Merged

**Pull request merged**
