### PR TITLE
Deprecate `detect` and `protect`. Add `git`, `dir`, `stdin`

### PR DESCRIPTION
**Pull request by zricethezav**
### Description:
This change deprecates `detect` and `protect` in favor of `git`, `dir,` and `stdin`. The three new commands more accurately represent what gitleaks is doing. This change is intended to be backwards compatible so `detect` and `protect` should continue working as intended. Here are some examples of command translations for this new version:

### Regular git scanning
```
// OLD CMD: gitleaks detect --source={repo}
// NEW CMD: gitleaks git {repo}
```

### Pre-commit scanning (not tracking staged changes)
```
// OLD CMD: gitleaks protect --source={repo}
// NEW CMD: gitleaks git --pre-commit {repo}
```

### Pre-commit scanning (tracking staged changes)
```
// OLD  CMD: gitleaks protect --staged --source={repo}
// NEW CMD: gitleaks git --pre-commit --staged {repo}
```

### Scanning directory/file
```
// OLD CMD: gitleaks detect --no-git --source={repo}
// NEW CMD: gitleaks directory {directory/file}
```

### Scanning piped data
```
// OLD CMD: gitleaks detect --no-git --pipe
// NEW CMD: cat {file} | ./gitleaks stdin -v
```

---

### Checklist:

* [x] Does your PR pass tests?
* [x] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by rgmz — COMMENTED** [review]
This makes sense, having to combine `detect`/`protect` with flags like `--no-git` always seemed a bit confusing.

**Comment by jtmilanest** [comment]
**NOT WORKING**
⚠️    ### **Error: File results.sarif does not exist** ⚠️ 

```gitleaks version: 8.19.0
Version to install: 8.19.0 (target directory: /tmp/gitleaks-8.19.0)
Received 2871291 of 2871291 ([10](https://github.com/meetearnest/infra-secrets/actions/runs/10859233286/job/30138287804#step:5:11)0.0%), 5.3 MBs/sec
Cache Size: ~3 MB (2871291 B)
/usr/bin/tar -z -xf /home/runner/work/_temp/03820656-bfd8-4ee7-b672-0613e645431e/cache.tgz -P -C /home/runner/work/infra-secrets/infra-secrets
Cache restored successfully
Gitleaks restored from cache
event type: push
gitleaks cmd: gitleaks detect --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif --log-level=debug --log-opts=-1
/tmp/gitleaks-8.19.0/gitleaks detect --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif --log-level=debug --log-opts=-1

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

3:37AM FTL flag accessed but not defined: source

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-[11](https://github.com/meetearnest/infra-secrets/actions/runs/10859233286/job/30138287804#step:5:12)-github-actions-deprecating-save-state-and-set-output-commands/
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:1850
            throw new Error(`File ${file} does not exist`);
                  ^

Error: File results.sarif does not exist
    at Object.getUploadSpecification (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:1850:19)
    at DefaultArtifactClient.<anonymous> (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:83:64)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:53:71
    at new Promise (<anonymous>)
    at __webpack_modules__.5327.__awaiter (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:49:[12](https://github.com/meetearnest/infra-secrets/actions/runs/10859233286/job/30138287804#step:5:13))
    at DefaultArtifactClient.uploadArtifact (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:78:16)
    at Object.Scan (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:70575:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/home/runner/work/_actions/gitleaks/gitleaks-action/v2.3.4/dist/index.js:7[13](https://github.com/meetearnest/infra-secrets/actions/runs/10859233286/job/30138287804#step:5:14)50:16)

Node.js v20.13.1```

**Comment by zricethezav** [comment]
@jtmilanest should be fixed in v8.19.1

**Comment by chopeen** [comment]
Should the hook definitions in [`.pre-commit-hooks.yaml`](https://github.com/gitleaks/gitleaks/blob/master/.pre-commit-hooks.yaml) be updated?

**Pull request merged**
