### PR TITLE
Make private key check less greedy and include fifth dash

### PR DESCRIPTION
**Pull request by bplaxco**
### Description:

Issue:

Private Key Regex is a bit greedy and if there is a file with a gitleaks:allow
between multiple keys it can cause them to be ignored.

Test file: https://github.com/leaktk/fake-leaks/blob/main/general-test

Before the change:

```
./gitleaks detect --no-git --source ~/debug/gitleaks/general-test  -v | grep OPENSSH

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

11:00AM INF scan completed in 27.1ms
11:00AM WRN leaks found: 100
```

After the change:

```
./gitleaks detect --no-git --source ~/debug/gitleaks/general-test  -v | grep OPENSSH

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

Finding:     fake_cert = '-----BEGIN OPENSSH PRIVATE KEY-----
Secret:      -----BEGIN OPENSSH PRIVATE KEY-----
11:02AM INF scan completed in 27.3ms
11:02AM WRN leaks found: 108
```

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes? 
   - **No:** There were already tests for private keys
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by bplaxco** [comment]
Ah I was wondering how the config generation worked. I'll get that fixed.

**Comment by bplaxco** [comment]
Okay, the tests pass (TIL I learned about `go generate`).

This should also resolve:

- https://github.com/gitleaks/gitleaks/pull/1351
- https://github.com/gitleaks/gitleaks/issues/1085

Let me know if there's anything else you'd like me to tweak about this @zricethezav

**Comment by bplaxco** [comment]
Hmm it didn't like something about the rebase I did. I'll get that sorted tomorrow

**Comment by zricethezav** [comment]
> Hmm it didn't like something about the rebase I did. I'll get that sorted tomorrow

@bplaxco I should probably make that "validate config" step a little more robust. Thanks for the PR!

**Pull request merged**
