### PR TITLE
Match left side of identifier

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This update the identifier pattern to include more context. This will make it easier to exclude false positives.

```diff
-"Match": "KeyToken=b77a5c561934e089\"",
+"Match": "PublicKeyToken=b77a5c561934e089\"",
 "Secret": "b77a5c561934e089",
```

Related: #1492 and #1578.

### Checklist:

* [ ] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by zricethezav** [comment]
Makes sense

**Comment by rgmz** [comment]
I can't think of a way this would negatively impact matching, but let's keep ours eyes peeled just in case.

**Comment by zricethezav** [comment]
Experimentation 👨‍🔬

**Comment by rgmz** [comment]
image

**Pull request merged**
