### PR TITLE
Detect base64-encoded JWTs

### PR DESCRIPTION
**Pull request by rgmz**
### Description:

This is a somewhat niche rule, but it is high confidence. It's been tested against all the standard JWT headers that I could find (e.g., https://www.iana.org/assignments/jose/jose.xhtml).

In retrospect, the rule itself could have been generated programmatically based on a list of header names. 😂 

### Checklist:

* [ ] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [ ] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by zricethezav** [comment]
@rgmz In theory I'm all for this rule, I just want to do some benchmarking to make sure we aren't introducing a rule that significantly slows down "typical" scans.

**Comment by zricethezav** [comment]
> @rgmz In theory I'm all for this rule, I just want to do some benchmarking to make sure we aren't introducing a rule that significantly slows down "typical" scans.

I should probably introduce a performance check in the CI anyways 🤷🏻

**Comment by rgmz** [comment]
> @rgmz In theory I'm all for this rule, I just want to do some benchmarking to make sure we aren't introducing a rule that significantly slows down "typical" scans.

I don't expect it would, but we could always add longer prefixes to the keywords. Though wasn't there an issue with overlapping keywords?

**Comment by zricethezav** [comment]
Performs great! No noticeable increase in memory or scan time. 

> I don't expect it would, but we could always add longer prefixes to the keywords. Though wasn't there an issue with overlapping keywords?

Fixed in https://github.com/gitleaks/gitleaks/pull/1259 :)

**Pull request merged**
