### PR TITLE
feat: Hashicorp Terraform fields for password

### LINKED ISSUE #1236: Hashicorp Terraform fields for password
**Describe the bug**
There is one specific rule for Hashicorp, and it requires the word `atlasv1` to be part of the secret.
I'm not an expert in Terraform, but I see a case when there is a dedicated field for a password in Azure MSSQL called `administrator_login_password`: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server.html

**To Reproduce**
Take this snippet and scan it with _gitleaks_:
```
resource "azurerm_resource_group" "example" {
  name     = "database-rg"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "examplesa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_sql_server" "example" {
  name                         = "mssqlserver"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"

  tags = {
    environment = "production"
  }
}
```

**Expected behavior**
Find the password `thisIsDog11` for `administrator_login_password`

**Basic Info (please complete the following information):**
 - Gitleaks Version: `master`

**Additional context**
I know that maybe the entropy of the password is low, but here is an example of a field that we know is a password. As far as I know, if it is not a password but a variable, it will be without quotes.

I can implement this, I just want to know how to structure it in the _Hashicorp_ rules, if we want to add a rule for each field like this, or consider this field name (`administrator_login_password`) as a _keyword_?

cc @zricethezav

### PR DESCRIPTION
**Pull request by baruchiro**
Fixes #1236

### Description:
You can find many examples of Terraform fields that accepts hard-coded password.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server.html
https://registry.terraform.io/providers/petoju/mysql/latest/docs

They are in format of `name          = "hard_coded_pass"`, and it didn't catched by the generic rule.

### Checklist:

* [x] Does your PR pass tests?
* [x] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by zricethezav — APPROVED** [review]
nice, thanks @baruchiro

**Comment by zricethezav** [comment]
@baruchiro would you mind resolving conflicts?

**Comment by baruchiro** [comment]
Yes I will

**Comment by baruchiro** [comment]
@zricethezav Done

**Comment by zricethezav** [comment]
@baruchiro could you look into the failing test?

**Comment by baruchiro** [comment]
@zricethezav ready

**Comment by Devvox93** [comment]
Why is this not merged yet? Seems like a good addition and checks and approvals are green.

**Pull request merged**
