### PR TITLE
validate report path before scan start

### PR DESCRIPTION
**Pull request by mesaglio**
### Description:
Solution for issue #1065.

### Checklist:

* [X] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [X] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by rgmz — COMMENTED** [review]
The error messages could be tweaked a bit, but this is a welcome QoL change otherwise.

**Comment by mesaglio** [comment]
@rgmz I update the error message.

**Comment by mesaglio** [comment]
@rgmz 🏓

**Comment by rgmz** [comment]
It's actually up to @zricethezav, I was just providing feedback.

**Comment by mesaglio** [comment]
@zricethezav 🏓

**Pull request closed without merging**
